import i18n from "@i18n"
import { i18n_alt } from "@functions/translators"

const equipmentTemplate = {
	helmet: null,
	leftHand: null,
	chest: null,
	rightHand: null,
	legs: null,
	leftFoot: null,
	rightFoot: null,
}

export default () => {
	const t = i18n.getFixedT(i18n.language, "characters")

	return [
		{
			id: 1,
			description: t("default.description"),
			img: "/src/assets/characters/default.svg",
			className: t("default.name"),
			money: 22,
			stones: 2,
			stats: {
				health: 16,
				armor: 0.2,
				critic: 25,
				dodge: 15,
				lucky: 1,
				karma: 0.5,
				trullyKarma: 0.625,
			},
			classEffects: {},
			equipment: {
				...equipmentTemplate,
				helmet: {
					id: 3,
					src: "/src/assets/armors/helmets/simple-helmet.svg",
					alt: i18n_alt({
						type: "helmet",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",

					equipType: "armor",
					type: "helmet",
					variant: "simple",
					price: 17,
					armor: 0.2,
					health: 2,
					passiveEffects: {},
				},
				leftHand: {
					id: 1,
					src: "/src/assets/weapons/swords/simple-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",

					equipType: "weapon",
					type: "sword",
					variant: "simple",
					price: 18,
					attack: 3,
					passiveEffects: {},
					activeEffects: {},
				},
			},
		},

		{
			id: 2,
			description: t("knight.description"),
			img: "/src/assets/characters/knight.svg",
			className: t("knight.name"),
			money: 12,
			stones: 4,
			stats: {
				health: 32,
				armor: 0.6,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
				trullyKarma: 1.5,
			},
			classEffects: {},
			equipment: {
				...equipmentTemplate,
				leftHand: {
					id: 1,
					src: "/src/assets/weapons/swords/simple-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipType: "weapon",
					type: "sword",
					variant: "simple",
					price: 16,
					attack: 3,
					passiveEffects: {},
					activeEffects: {},
				},
				helmet: {
					id: 2,
					src: "/src/assets/armors/helmets/simple-helmet.svg",
					alt: i18n_alt({
						type: "helmet",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipType: "armor",
					type: "helmet",
					variant: "simple",
					price: 15,
					armor: 0.2,
					health: 3,
					passiveEffects: {},
				},
				chest: {
					id: 3,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipType: "armor",
					type: "chest",
					variant: "simple",
					price: 17,
					armor: 0.2,
					health: 5,
					passiveEffects: {},
				},
				legs: {
					id: 4,
					src: "/src/assets/armors/legs/simple-legs.svg",
					alt: i18n_alt({ type: "legs", quality: "common", variant: "simple" }),
					quality: "common",
					equipType: "armor",
					type: "legs",
					variant: "simple",
					price: 16,
					armor: 0.2,
					health: 4,
					passiveEffects: {},
				},
			},
		},
		{
			id: 3,
			description: t("hammerBro.description"),
			img: "/src/assets/characters/hammer-bro.svg",
			className: t("hammerBro.name"),
			money: 32,
			stones: 4,
			stats: {
				health: 21,
				armor: 0.2,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
				trullyKarma: 1.5,
			},
			classEffects: {
				extraHammerDamage: 0.2,
			},
			equipment: {
				...equipmentTemplate,
				leftHand: {
					id: 1,
					src: "/src/assets/weapons/hammers/lucky-hammer.svg",
					alt: i18n_alt({
						type: "hammer",
						quality: "common",
						variant: "lucky",
					}),
					quality: "rare",
					equipType: "weapon",
					type: "hammer",
					variant: "lucky",
					price: 14,
					attack: 4,
					passiveEffects: {
						hammerDamageMultiplier: 0.1,
					},
					activeEffects: {},
				},
				chest: {
					id: 2,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipType: "armor",
					type: "chest",
					variant: "simple",
					price: 15,
					health: 5,
					armor: 0.2,
					passiveEffects: {},
				},
			},
		},

		{
			id: 99,
			description: t("developer.description"),
			img: "/src/assets/characters/dev.svg",
			className: t("developer.name"),
			money: 2000,
			stones: 2000,
			stats: {
				health: 100,
				armor: 1,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
				trullyKarma: 1.5,
			},
			classEffects: { extraHammerDamage: 0.2 },
			equipment: {
				...equipmentTemplate,
				leftHand: {
					id: 1,
					src: "/src/assets/weapons/hammers/bloody-hammer.svg",
					alt: i18n_alt({
						type: "hammer",
						quality: "common",
						variant: "bloody",
					}),
					quality: "common",
					equipType: "weapon",
					type: "hammer",
					variant: "bloody",
					price: 16,
					attack: 3,
					passiveEffects: {
						hammerDamageMultiplier: 0.1,
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						lifeSteal: 0.2,
					},
				},
				rightHand: {
					id: 2,
					src: "/src/assets/weapons/swords/critic-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "lethal",
					}),
					quality: "common",

					equipType: "weapon",
					type: "sword",
					variant: "lethal",
					price: 15,
					attack: 3,
					passiveEffects: {
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						superCritic: 0.2,
					},
				},
				legs: {
					id: 4,
					src: "/src/assets/armors/legs/simple-legs.svg",
					alt: i18n_alt({ type: "legs", quality: "common", variant: "simple" }),
					quality: "common",

					equipType: "armor",
					type: "legs",
					variant: "simple",
					price: 16,
					armor: 0.2,
					health: 4,
					passiveEffects: {
						luckyStatMultiplier: 0.1,
					},
				},
				chest: {
					id: 5,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",

					equipType: "armor",
					type: "chest",
					variant: "simple",
					price: 17,
					armor: 0.2,
					health: 4,
					passiveEffects: {
						extraArmor: 0.1,
					},
				},
			},
			backpag: [
				{
					id: 3,
					src: "/src/assets/weapons/swords/strongest-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "rare",
						variant: "strong",
					}),
					quality: "rare",
					equipType: "weapon",
					type: "sword",
					variant: "strong",
					price: 47,
					attack: 5,
					passiveEffects: {
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						strongestAttack: 0.2,
					},
				},
				{
					id: 6,
					src: "/src/assets/weapons/sables/strong-sable.svg",
					alt: i18n_alt({
						type: "sable",
						quality: "rare",
						variant: "strong",
					}),
					quality: "rare",
					equipType: "weapon",
					type: "sable",
					variant: "strong",
					price: 47,
					attack: 5,
					passiveEffects: {},
					activeEffects: {
						stoleMoney: 3,
						strongestAttack: 0.2,
					},
				},
			],
		},
	]
}
