export const WHEEL_OPTIONS_SCALE_BY_TRULLYKARMA = 1

export const CRITIC_PROB_SCALE_BY_TRULLYKARMA = 3

export const MONEY_REWARD_BY_TRULLYKARMA = 1.5

export const STONES_REWARD_BY_TRULLYKARMA = 0.5

export const LUCKY_FOR_TRULLYKARMA = 0.3

export const KARMA_FOR_TRULLYKARMA = 2

export const DODGE_PROB_BY_TRULLYKARMA = 2.5
