import i18n from "../shared/translates/i18n"
import { i18n_alt } from "../shared/translates/translators"

export default () => {
	const t = i18n.getFixedT(i18n.language, "characters")

	return [
		{
			id: 1,
			description: t("default.description"),
			img: "/src/assets/characters/default.svg",
			name: t("default.name"),
			money: 22,
			stones: 2,
			stats: {
				health: 16,
				armor: 0.2,
				critic: 25,
				dodge: 15,
				lucky: 1,
				karma: 0.5,
				trullyKarma: 0.5,
			},
			classEffects: {},
			items: [
				{
					id: 3,
					src: "/src/assets/armors/helmets/lucky-helmet.svg",
					alt: i18n_alt({
						type: "helmet",
						quality: "common",
						variant: "lucky",
					}),
					quality: "common",
					equipKey: "helmet",
					equipType: "armor",
					type: "helmet",
					armor: 0.2,
					health: 2,
					passiveEffects: {},
				},
				{
					id: 1,
					src: "/src/assets/weapons/swords/simple-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "leftHand",
					equipType: "weapon",
					type: "sword",
					attack: 3,
					passiveEffects: {},
					activeEffects: {},
				},
			],
		},

		{
			id: 2,
			description: t("knight.description"),
			img: "/src/assets/characters/knight.svg",
			name: t("knight.name"),
			money: 12,
			stones: 4,
			stats: {
				health: 32,
				armor: 0.6,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
			},
			classEffects: {},
			items: [
				{
					id: 1,
					src: "/src/assets/weapons/swords/simple-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "leftHand",
					type: "sword",
					attack: 3,
					passiveEffects: {},
					activeEffects: {},
				},
				{
					id: 2,
					src: "/src/assets/armors/helmets/simple-helmet.svg",
					alt: i18n_alt({
						type: "helmet",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "helmet",
					equipType: "armor",
					type: "helmet",
					armor: 0.2,
					health: 3,
					passiveEffects: {},
				},
				{
					id: 3,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "chest",
					equipType: "armor",
					type: "chest",
					armor: 0.2,
					health: 5,
					passiveEffects: {},
				},
				{
					id: 4,
					src: "/src/assets/armors/legs/simple-legs.svg",
					alt: i18n_alt({ type: "legs", quality: "common", variant: "simple" }),
					quality: "common",
					equipKey: "legs",
					equipType: "armor",
					type: "legs",
					armor: 0.2,
					health: 4,
					passiveEffects: {},
				},
			],
		},
		{
			id: 3,
			description: t("hammerBro.description"),
			img: "/src/assets/characters/hammer-bro.svg",
			name: t("hammerBro.name"),
			money: 32,
			stones: 4,
			stats: {
				health: 21,
				armor: 0.2,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
			},
			classEffects: {
				extraHammerDamage: 0.2,
			},
			items: [
				{
					id: 1,
					src: "/src/assets/weapons/hammers/lucky-hammer.svg",
					alt: i18n_alt({
						type: "hammer",
						quality: "common",
						variant: "lucky",
					}),
					quality: "rare",
					equipKey: "leftHand",
					equipType: "weapon",
					type: "hammer",
					attack: 4,
					passiveEffects: {
						hammerDamageMultiplier: 0.1,
					},
					activeEffects: {},
				},
				{
					id: 2,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "chest",
					equipType: "armor",
					type: "chest",
					health: 5,
					armor: 0.2,
					passiveEffects: {},
				},
			],
		},

		{
			id: 99,
			description: t("developer.description"),
			img: "/src/assets/characters/dev.svg",
			name: t("developer.name"),
			money: 2000,
			stones: 2000,
			stats: {
				health: 100,
				armor: 1,
				critic: 25,
				dodge: 25,
				lucky: 2,
				karma: 1,
			},
			classEffects: { extraHammerDamage: 0.2 },
			items: [
				{
					id: 1,
					src: "/src/assets/weapons/hammers/bloody-hammer.svg",
					alt: i18n_alt({
						type: "hammer",
						quality: "common",
						variant: "bloody",
					}),
					quality: "common",
					equipKey: "leftHand",
					equipType: "weapon",
					type: "hammer",
					attack: 3,
					passiveEffects: {
						hammerDamageMultiplier: 0.1,
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						lifeSteal: 0.2,
					},
				},
				{
					id: 2,
					src: "/src/assets/weapons/swords/critic-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "common",
						variant: "critic",
					}),
					quality: "common",
					equipKey: "rightHand",
					equipType: "weapon",
					type: "sword",
					attack: 3,
					passiveEffects: {
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						superCritic: 0.2,
					},
				},

				{
					id: 4,
					src: "/src/assets/armors/legs/simple-legs.svg",
					alt: i18n_alt({ type: "legs", quality: "common", variant: "simple" }),
					quality: "common",
					equipKey: "legs",
					equipType: "armor",
					type: "legs",
					armor: 0.2,
					health: 4,
					passiveEffects: {
						luckyStatMultiplier: 0.1,
					},
				},
				{
					id: 5,
					src: "/src/assets/armors/chests/simple-chest.svg",
					alt: i18n_alt({
						type: "chest",
						quality: "common",
						variant: "simple",
					}),
					quality: "common",
					equipKey: "chest",
					equipType: "armor",
					type: "chest",
					armor: 0.2,
					health: 4,
					passiveEffects: {
						extraArmor: 0.1,
					},
				},
			],
			backpag: [
				{
					id: 3,
					src: "/src/assets/weapons/swords/strongest-sword.svg",
					alt: i18n_alt({
						type: "sword",
						quality: "rare",
						variant: "strongest",
					}),
					quality: "rare",
					equipType: "weapon",
					type: "sword",
					attack: 5,
					passiveEffects: {
						luckyHitMultiplier: 0.1,
					},
					activeEffects: {
						strongestAttack: 0.2,
					},
				},
			],
		},
	]
}
